[package]
name = "chcookie"
version = "0.1.0"
authors = ["Kentaro Iwata"]
edition = "2018"
description = "Get Chrome Cookie command"

[dependencies]
keyring = "0.9.0"
rust-crypto = "0.2.36"
aes = "0.3.2"
block-modes = "0.3.3"
rusqlite = "0.23.1"
dirs = "2.0.2"
clap = "2.33.1"
